# Autoscaler's deployment MUST be:
#   name: camunda-autoscaler
#   namespace: default
#   image: local.registry/camunda-autoscaler:1.0.0
#   imagePullPolicy: IfNotPresent

# otherwise the test framework won't find it and kind cluster won't be able to pull it

apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-account
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: scaler-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - pods
  verbs:
  - patch
  - get
  - list
  - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaler-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: autoscaler-account
  apiGroup: ""
roleRef:
  kind: Role
  name: scaler-role
  apiGroup: ""


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-autoscaler
  namespace: default
  labels:
    app: camunda
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      serviceAccountName: autoscaler-account
      containers:
      - name: camunda-autoscaler
        image: local.registry/camunda-autoscaler:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: CAMUNDA_URL
          value: "http://camunda-service:8080/engine-rest/history/process-instance/count"